version: "3.3"

services:
  back_end:
    build: .
    ports:
        - "80:3000"
    environment:
        - LOTTO_BOT_TOKEN=$LOTTO_BOT_TOKEN
    volumes:
        - db:/usr/src/app/lotto_bot/data
volumes:
    db: {}
