version: "3.3"

services:
  db:
    image: mysql
    restart: always
    networks:
      - lotto_net
    volumes:
      - type: volume
        source: dbdata
        target: /data/db

  front_end:
    image: sporter14/discord_lotto_bot:latest
    ports:
      - "80:3000"
    networks:
      - lotto_net
    environment:
      - DB_URL=mongodb://db:27017
      - DEBUG=app:*

networks:
  lotto_net:

volumes:
  dbdata:
