version: "3.3"

services:
    back_end:
        build: .
        ports:
            - "80:3000"
        environment:
            - LOTTO_BOT_TOKEN=$LOTTO_BOT_TOKEN
        volumes:
            - db:/usr/src/app/lotto_bot/data
    ouroboros:
        container_name: ouroboros
        hostname: ouroboros
        image: pyouroboros/ouroboros
        environment:
          - CLEANUP=true
          - INTERVAL=300
          - LOG_LEVEL=info
          - SELF_UPDATE=true
          - IGNORE=mongo influxdb postgres mariadb
          - TZ=America/Chicago
        restart: unless-stopped
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock

volumes:
    db: {}
